import {
  Document, Page, Text, View, StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page:     { fontFamily: "Helvetica", padding: 40, backgroundColor: "#fff" },
  title:    { fontSize: 20, fontWeight: "bold", color: "#c8102e", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#888", marginBottom: 20 },
  section:  { marginBottom: 16 },
  h2:       { fontSize: 13, fontWeight: "bold", marginBottom: 8, color: "#222" },
  row:      { flexDirection: "row", marginBottom: 5 },
  label:    { width: 140, fontSize: 10, color: "#666" },
  value:    { fontSize: 10, color: "#111" },
  divider:  { borderBottom: "1 solid #e0e0e0", marginVertical: 12 },
});

interface Props {
  eventName: string;
  venue: string;
  date: string;
  kpis: {
    registered: number; checkedIn: number; donated: number;
    deferred: number; noShow: number; conversionPct: number;
  };
  bloodGroups: { name: string; value: number }[];
}

export function EventReportPDF({ eventName, venue, date, kpis, bloodGroups }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{eventName}</Text>
        <Text style={styles.subtitle}>{venue} · {date}</Text>
        <View style={styles.divider} />
        <View style={styles.section}>
          <Text style={styles.h2}>Key Performance Indicators</Text>
          {([
            ["Registered",   kpis.registered],
            ["Checked In",   kpis.checkedIn],
            ["Donated",      kpis.donated],
            ["Deferred",     kpis.deferred],
            ["No-Show",      kpis.noShow],
            ["Conversion",   `${kpis.conversionPct}%`],
          ] as [string, string | number][]).map(([label, value]) => (
            <View key={label} style={styles.row}>
              <Text style={styles.label}>{label}</Text>
              <Text style={styles.value}>{String(value)}</Text>
            </View>
          ))}
        </View>
        {bloodGroups.length > 0 && (
          <>
            <View style={styles.divider} />
            <View style={styles.section}>
              <Text style={styles.h2}>Blood Group Distribution (Donated)</Text>
              {bloodGroups.map(bg => (
                <View key={bg.name} style={styles.row}>
                  <Text style={styles.label}>{bg.name}</Text>
                  <Text style={styles.value}>{bg.value}</Text>
                </View>
              ))}
            </View>
          </>
        )}
        <View style={styles.divider} />
        <Text style={{ fontSize: 8, color: "#bbb" }}>
          Generated by BeTheHero · {new Date().toLocaleString("en-IN")}
        </Text>
      </Page>
    </Document>
  );
}
